---
- block:

- name: install snaps with classic bound
  snap:
    name:
      - helm
      - kubectl
      - fluxctl
    classic: yes

  when: install_devops_toolbelt

- block:

- name: install snaps
  snap:
    name:
    - spotify
    - alacritty
    - bitwarden
    - code
    - signal-desktop
    - jdownloader2
    - mikrok8s
  when: use_snaps
