- block:

  # - name: Check for Atom
  #   stat: path=/usr/bin/atom
  #   register: atom_installed

  - name: Download Atom deb package
    get_url:
      url: https://atom.io/download/deb
      dest: /tmp/atom.deb
    when: not atom_installed.stat.exists

  - name: Install Atom deb package
    package:
      name: /tmp/atom.deb
      state: present
    when: not atom_installed.stat.exists

  when: (ansible_facts['os_family'] == "Debian") and (install_atom == true)
